export const LIMITS = {
  MAX: {
    USERNAME_CHARACTER_LENGTH: 16,
    PASSWORD_CHARACTER_LENGTH: 32,
    EMAIL_CHARACTER_LENGTH: 64,
    PROJECT_NAME_CHARACTER_LENGTH: 16,
    PROJECT_DOMAIN_CHARACTER_LENGTH: 28,
    PROJECT_LENGTH: 313131,
    PROJECT_LENGHTS: {
      FREE: 2,
      PRO: 4,
      ENTERPRISE: 99999,
    },
    LOG_USAGE_LIMIT: 313131,
    LOG_USAGE_LIMITS: {
      FREE: 2000,
      PRO: 100000,
      ENTERPRISE: 999999,
    },
    PROJECT_LOG_SEARCH_TEXT_LENGTH: 32,
    BATCH_USAGE_LIMITS: {
      FREE: 100,
      PRO: 2000,
      ENTERPRISE: 999999,
    },
  },
  MIN: {
    USERNAME_CHARACTER_LENGTH: 3,
    PASSWORD_CHARACTER_LENGTH: 6,
    EMAIL_CHARACTER_LENGTH: 6,
    PROJECT_NAME_CHARACTER_LENGTH: 3,
    PROJECT_DOMAIN_CHARACTER_LENGTH: 4,
  },
};
