export const LIMITS = {
  MAX: {
    USERNAME_CHARACTER_LENGTH: 16,
    PASSWORD_CHARACTER_LENGTH: 32,
    EMAIL_CHARACTER_LENGTH: 64,
    PROJECT_NAME_CHARACTER_LENGTH: 16,
    PROJECT_DOMAIN_CHARACTER_LENGTH: 28,
    PROJECT_LENGTH: 10,
    PROJECT_LOG_SEARCH_TEXT_LENGTH: 32,
    LOG_USAGE_LIMIT: 100000,
  },
  MIN: {
    USERNAME_CHARACTER_LENGTH: 3,
    PASSWORD_CHARACTER_LENGTH: 6,
    EMAIL_CHARACTER_LENGTH: 6,
    PROJECT_NAME_CHARACTER_LENGTH: 3,
    PROJECT_DOMAIN_CHARACTER_LENGTH: 4,
  },
};
